name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-386:
    name: windows-386
    runs-on: ubuntu-latest
    steps:
      - name: Set the Version
        id: data
        run: echo "::set-output name=version::`date +%Y.%m.%d`"
      - name: Display the Version
        run: echo ${{steps.data.outputs.version}}
      - uses: actions/checkout@master
      - name: Compile and Release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: 386
          GOOS: windows
          CMD_PATH: .
          EXTRA_FILES: README.md
          PROJECT_NAME: psftp
          RELEASE_NAME: ${{steps.date.outputs.version}}

  build-windows-amd64:
    name: windows-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Set the Version
        id: data
        run: echo "::set-output name=version::`date +%Y.%m.%d`"
      - name: Display the Version
        run: echo ${{steps.data.outputs.version}}
      - uses: actions/checkout@master
      - name: Compile and Release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: windows
          CMD_PATH: .
          EXTRA_FILES: README.md
          PROJECT_NAME: psftp
          RELEASE_NAME: ${{steps.date.outputs.version}}
