name: psftp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-386:
    name: windows-386
    runs-on: ubuntu-latest
    steps:
      - name: Set the Version
        id: version
        run: echo "::set-output name=version::`date +%Y.%m.%d`"
      - uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: psftp-x86-${{steps.version.outputs.version}}
          body: ""
          draft: false
          prerelease: false
      - name: Compile and Release
        uses: ngs/go-release.action@v1.0.1
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./psftp-x86-${{steps.version.outputs.version}}.zip
          asset_name: psftp-x86-${{steps.version.outputs.version}}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GOARCH: 386
          GOOS: windows
          CMD_PATH: .
          EXTRA_FILES: README.md
          PROJECT_NAME: psftp
          RELEASE_NAME: ${{steps.version.outputs.version}}
