name: psftp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-386:
    name: windows-386
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PSFTP_VERSION: "$(date +%Y.%m.%d)${GITHUB_SHA:4}"
    steps:
      - name: Show the Version
        run: echo $PSFTP_VERSION
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Create the Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $PSFTP_VERSION
          release_name: psftp-x86-$PSFTP_VERSION
          body: ""
          draft: false
          prerelease: false
      - name: Compile and Release
        uses: ngs/go-release.action@v1.0.1
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./psftp-x86-$PSFTP_VERSION.zip
          asset_name: psftp-x86-$PSFTP_VERSION.zip
          asset_content_type: application/zip
        env:
          GOARCH: 386
          GOOS: windows
          CMD_PATH: .
          EXTRA_FILES: README.md
          PROJECT_NAME: psftp
          RELEASE_NAME: ${{steps.version.outputs.version}}
