on: [ push, pull_request ]

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      UPLOAD_GIT: ${{secrets.UPLOAD_GIT}}
      UPLOAD_KEY: ${{secrets.UPLOAD_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Upload
        uses: ./
