on: [ push, pull_request ]

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Environment
        run: |
          echo "::set-env name=GIT_LOG::$(git log --pretty=oneline)"
          echo "::set-env name=PROJECT_VERSION::$(date +%Y.%m.%d).$(echo ${GITHUB_SHA} | cut -c1-4)"
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: ./
      - name: Release
        id: create
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.PROJECT_VERSION}}
          release_name: psftp-${{env.PROJECT_VERSION}}
          body: ${{env.GIT_LOG}}
          draft: true
          prerelease: true
    - name: Upload
      uses: csexton/release-asset-action@v2
      with:
        pattern: "${{env.BUILD_DIR}}/*"
        github-token: ${{secrets.GITHUB_TOKEN}}
        release-url: ${{steps.release.outputs.upload_url}}
