on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Prepare
        run: wget https://raw.githubusercontent.com/calebgray/psftp/master/.github/actions/psftp/Dockerfile
      - name: Build
        uses: ./
      - name: Environment
        run: env
      - name: Filesystem
        run: find /
