on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-x86:
    name: windows-x86
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PROJECT_NAME: psftp
      GOARCH: 386
      GOOS: windows
      CGO_ENABLED: 1
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Setup Environment
        run: |
          echo "::set-env name=GIT_LOG::$(git log --pretty=oneline)"
          echo "::set-env name=PROJECT_VERSION::$(date +%Y.%m.%d)${GITHUB_SHA:4}"
      - name: Create the Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.PROJECT_VERSION}}
          release_name: psftp-x86-${{env.PROJECT_VERSION}}
          body: ${{env.GIT_LOG}}
          draft: true
          prerelease: true
      - name: Build and Upload
        run: sudo -E build/github.sh
