on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win32:
    name: win32
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GOARCH: 386
      GOOS: windows
      CGO_ENABLED: 1
      OUTPUT_SUFFIX: .exe
    steps:
      - name: Checkout the Sources
        uses: actions/checkout@master
      - name: Setup Environment
        run: |
          echo "::set-env name=GIT_LOG::$(git log --pretty=oneline)"
          echo "::set-env name=PROJECT_VERSION::$(date +%Y.%m.%d).$(echo ${GITHUB_SHA} | cut -c1-4)"
          echo "::set-env name=OUTPUT_NAME::psftp-x86-${PROJECT_VERSION}"
      - name: Create the Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{env.PROJECT_VERSION}}
          release_name: psftp-x86-${{env.PROJECT_VERSION}}
          body: ${{env.GIT_LOG}}
          draft: true
          prerelease: false
      - name: Build the Release
        id: build
        run: sudo -E build/github.sh
      - name: Upload the Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./${{env.OUTPUT_NAME}}.zip
          asset_name: ${{env.OUTPUT_NAME}}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
