on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-x86:
    name: windows-x86
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PROJECT_VERSION: "$(date +%Y.%m.%d)${GITHUB_SHA:4}"
      PROJECT_NAME: psftp
      GOARCH: 386
      GOOS: windows
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Create the Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "$PROJECT_VERSION"
          release_name: "psftp-x86-$PROJECT_VERSION"
          body: "$(git log --pretty=oneline)"
          draft: true
          prerelease: true
      - name: Build and Release
        uses: ./Dockerfile
