on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: ./.github/actions/psftp
      - name: Environment
        run: env
      - name: Filesystem
        run: find /
